#Naming the application & Gateway locator for Eureka
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#Configuring the server port
server:
  port: 8080

#Eureka related properties
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

#Spring Actuator related properties
management:
  endpoints:
    web:
      exposure:
        include:
          - true