#Naming the application
spring:
  application:
    name: service-registration

#Configuring the server port
server:
  port: 8761

#Eureka related properties
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
  instance:
    hostname: localhost